services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend/db.json:/app/db.json
    networks:
      - jsa-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - jsa-network

networks:
  jsa-network:
    driver: bridge
